/**
 * Stellar DataStore
 * The Stellar DataStore service is your instantly available, secure and worry-free cloud data storage service. Sign-up now and minutes later, you can start putting your data in the cloud.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateRecordRequest model module.
 * @module model/CreateRecordRequest
 * @version v1
 */
class CreateRecordRequest {
    /**
     * Constructs a new <code>CreateRecordRequest</code>.
     * @alias module:model/CreateRecordRequest
     * @param records {Array.<Object.<String, Object>>} 
     */
    constructor(records) { 
        
        CreateRecordRequest.initialize(this, records);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, records) { 
        obj['records'] = records;
    }

    /**
     * Constructs a <code>CreateRecordRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateRecordRequest} obj Optional instance to populate.
     * @return {module:model/CreateRecordRequest} The populated <code>CreateRecordRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateRecordRequest();

            if (data.hasOwnProperty('records')) {
                obj['records'] = ApiClient.convertToType(data['records'], [{'String': Object}]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateRecordRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateRecordRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateRecordRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['records'])) {
            throw new Error("Expected the field `records` to be an array in the JSON data but got " + data['records']);
        }

        return true;
    }


}

CreateRecordRequest.RequiredProperties = ["records"];

/**
 * @member {Array.<Object.<String, Object>>} records
 */
CreateRecordRequest.prototype['records'] = undefined;






export default CreateRecordRequest;

