/**
 * Stellar DataStore
 * The Stellar DataStore service is your instantly available, secure and worry-free cloud data storage service. Sign-up now and minutes later, you can start putting your data in the cloud.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RevokeTokenRequest model module.
 * @module model/RevokeTokenRequest
 * @version v1
 */
class RevokeTokenRequest {
    /**
     * Constructs a new <code>RevokeTokenRequest</code>.
     * @alias module:model/RevokeTokenRequest
     * @param refreshToken {String} 
     * @param clientId {String} 
     * @param clientSecret {String} 
     */
    constructor(refreshToken, clientId, clientSecret) { 
        
        RevokeTokenRequest.initialize(this, refreshToken, clientId, clientSecret);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, refreshToken, clientId, clientSecret) { 
        obj['refresh_token'] = refreshToken;
        obj['client_id'] = clientId;
        obj['client_secret'] = clientSecret;
    }

    /**
     * Constructs a <code>RevokeTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RevokeTokenRequest} obj Optional instance to populate.
     * @return {module:model/RevokeTokenRequest} The populated <code>RevokeTokenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RevokeTokenRequest();

            if (data.hasOwnProperty('refresh_token')) {
                obj['refresh_token'] = ApiClient.convertToType(data['refresh_token'], 'String');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('client_secret')) {
                obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RevokeTokenRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RevokeTokenRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RevokeTokenRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['refresh_token'] && !(typeof data['refresh_token'] === 'string' || data['refresh_token'] instanceof String)) {
            throw new Error("Expected the field `refresh_token` to be a primitive type in the JSON string but got " + data['refresh_token']);
        }
        // ensure the json data is a string
        if (data['client_id'] && !(typeof data['client_id'] === 'string' || data['client_id'] instanceof String)) {
            throw new Error("Expected the field `client_id` to be a primitive type in the JSON string but got " + data['client_id']);
        }
        // ensure the json data is a string
        if (data['client_secret'] && !(typeof data['client_secret'] === 'string' || data['client_secret'] instanceof String)) {
            throw new Error("Expected the field `client_secret` to be a primitive type in the JSON string but got " + data['client_secret']);
        }

        return true;
    }


}

RevokeTokenRequest.RequiredProperties = ["refresh_token", "client_id", "client_secret"];

/**
 * @member {String} refresh_token
 */
RevokeTokenRequest.prototype['refresh_token'] = undefined;

/**
 * @member {String} client_id
 */
RevokeTokenRequest.prototype['client_id'] = undefined;

/**
 * @member {String} client_secret
 */
RevokeTokenRequest.prototype['client_secret'] = undefined;






export default RevokeTokenRequest;

