/**
 * Stellar DataStore
 * The Stellar DataStore service is your instantly available, secure and worry-free cloud data storage service. Sign-up now and minutes later, you can start putting your data in the cloud.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ServiceMessageType.
* @enum {}
* @readonly
*/
export default class ServiceMessageType {
    
        /**
         * value: 10
         * @const
         */
        "10" = 10;

    
        /**
         * value: 20
         * @const
         */
        "20" = 20;

    
        /**
         * value: 30
         * @const
         */
        "30" = 30;

    
        /**
         * value: 31
         * @const
         */
        "31" = 31;

    
        /**
         * value: 32
         * @const
         */
        "32" = 32;

    

    /**
    * Returns a <code>ServiceMessageType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ServiceMessageType} The enum <code>ServiceMessageType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

