/**
 * Stellar DataStore
 * The Stellar DataStore service is your instantly available, secure and worry-free cloud data storage service. Sign-up now and minutes later, you can start putting your data in the cloud.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import FieldRequest from '../model/FieldRequest';
import FieldResponseServiceResult from '../model/FieldResponseServiceResult';
import IServiceResult from '../model/IServiceResult';
import ServiceResult from '../model/ServiceResult';

/**
* Field service.
* @module api/FieldApi
* @version v1
*/
export default class FieldApi {

    /**
    * Constructs a new FieldApi. 
    * @alias module:api/FieldApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1SchemaTableFieldDelete operation.
     * @callback module:api/FieldApi~v1SchemaTableFieldDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes the given field within the given table.
     * @param {String} project The project containing the table.
     * @param {Number} table The table containing the given field.
     * @param {Number} field The field to be deleted
     * @param {module:api/FieldApi~v1SchemaTableFieldDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    v1SchemaTableFieldDelete(project, table, field, callback) {
      let postBody = null;
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling v1SchemaTableFieldDelete");
      }
      // verify the required parameter 'table' is set
      if (table === undefined || table === null) {
        throw new Error("Missing the required parameter 'table' when calling v1SchemaTableFieldDelete");
      }
      // verify the required parameter 'field' is set
      if (field === undefined || field === null) {
        throw new Error("Missing the required parameter 'field' when calling v1SchemaTableFieldDelete");
      }

      let pathParams = {
      };
      let queryParams = {
        'project': project,
        'table': table,
        'field': field
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/schema/table/field', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1SchemaTableFieldGet operation.
     * @callback module:api/FieldApi~v1SchemaTableFieldGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/IServiceResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets field(s) from given table.
     * @param {String} project The project containing the table.
     * @param {Number} table The table containing the fields.
     * @param {Object} opts Optional parameters
     * @param {Number} [field] The optional field to get.
     * @param {module:api/FieldApi~v1SchemaTableFieldGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/IServiceResult}
     */
    v1SchemaTableFieldGet(project, table, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling v1SchemaTableFieldGet");
      }
      // verify the required parameter 'table' is set
      if (table === undefined || table === null) {
        throw new Error("Missing the required parameter 'table' when calling v1SchemaTableFieldGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'project': project,
        'table': table,
        'field': opts['field']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = IServiceResult;
      return this.apiClient.callApi(
        '/v1/schema/table/field', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1SchemaTableFieldPost operation.
     * @callback module:api/FieldApi~v1SchemaTableFieldPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FieldResponseServiceResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds a field to the given table.
     * @param {String} project The project containing the table.
     * @param {Number} table The table to be added to.
     * @param {Object} opts Optional parameters
     * @param {module:model/FieldRequest} [fieldRequest] 
     * @param {module:api/FieldApi~v1SchemaTableFieldPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FieldResponseServiceResult}
     */
    v1SchemaTableFieldPost(project, table, opts, callback) {
      opts = opts || {};
      let postBody = opts['fieldRequest'];
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling v1SchemaTableFieldPost");
      }
      // verify the required parameter 'table' is set
      if (table === undefined || table === null) {
        throw new Error("Missing the required parameter 'table' when calling v1SchemaTableFieldPost");
      }

      let pathParams = {
      };
      let queryParams = {
        'project': project,
        'table': table
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = FieldResponseServiceResult;
      return this.apiClient.callApi(
        '/v1/schema/table/field', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1SchemaTableFieldPut operation.
     * @callback module:api/FieldApi~v1SchemaTableFieldPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FieldResponseServiceResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the given field in the given table.
     * @param {String} project The project containing the table.
     * @param {Number} table The table containing the field.
     * @param {Number} field The field to be updated.
     * @param {Object} opts Optional parameters
     * @param {module:model/FieldRequest} [fieldRequest] 
     * @param {module:api/FieldApi~v1SchemaTableFieldPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FieldResponseServiceResult}
     */
    v1SchemaTableFieldPut(project, table, field, opts, callback) {
      opts = opts || {};
      let postBody = opts['fieldRequest'];
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling v1SchemaTableFieldPut");
      }
      // verify the required parameter 'table' is set
      if (table === undefined || table === null) {
        throw new Error("Missing the required parameter 'table' when calling v1SchemaTableFieldPut");
      }
      // verify the required parameter 'field' is set
      if (field === undefined || field === null) {
        throw new Error("Missing the required parameter 'field' when calling v1SchemaTableFieldPut");
      }

      let pathParams = {
      };
      let queryParams = {
        'project': project,
        'table': table,
        'field': field
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = FieldResponseServiceResult;
      return this.apiClient.callApi(
        '/v1/schema/table/field', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
